language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.5
  - jruby
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - rake --version
before_script:
  - bundle exec rake --version
script: bundle exec rake tests
env:
  global:
    - CI="travis"
    - JRUBY_OPTS="--server -J-Xms512m -J-Xmx2G"
branches:
  only:
    - master
